### ISSUE TITLE
Config example for home assistant PE device.

### ISSUE THREAD

**Issue by slazix54** [eslavnov/ttmg_server#17]
If someone could give me a config example of what my home assistant voice pe xxxx yaml is supposed to look like? I'm think my config is causing it to not load external components :/.

**Comment by eslavnov** [comment]
See my example below. 

```
substitutions:
  name: home-assistant-voice-09645e
  friendly_name: Home Assistant Voice Living Room
packages:
  # You might need to add '@25.2.0' at the end to ensure it works as expected
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml@25.2.0
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: %some_encryption_key%

# Load TTMG Server's custom components
external_components:
  - source:
      type: local
      path: /config/esphome_custom_components/e430d04de4dd7542f45e6147e6d5595e/

media_player:
  - platform: speaker
    id: !extend external_media_player
    # MP3 support
    announcement_pipeline:
      speaker: announcement_resampling_speaker
      format: MP3 
    # Custom wake word triggered sound
    files:
      - id: !extend wake_word_triggered_sound
        file: https://github.com/eslavnov/voice_playground/raw/refs/heads/main/wake_word_triggered.mp3
```
