### ISSUE TITLE
[Please vote] New feature: do not break other TTS for voice assistants on HAVPE devices

### ISSUE THREAD

**Issue by eslavnov** [eslavnov/ttmg_server#3]
The current approach breaks using other TTS engines with voice assistants on the HAVPE devices. What does it mean?
1. With the modified firmware, you can't use any other TTS engine except for the TTMG TTS in HASS voice assistant settings (it overwrites the default TTS url to listen to the TTMG Server instead of HASS). Your Text-to-speech engine should always be `TTMG TTS` in the following HASS voice assistant settings:
![Image](https://github.com/user-attachments/assets/3c0093fe-3e83-45b1-8ad0-c5bfaf1be34e)
2. All other TTS-related commands will work with other TTS engines, so something like this works even with the modified firmware:
```
action: tts.speak
metadata: {}
data:
  media_player_entity_id: media_player.home_assistant_voice_preview_edition
  message: Some kind of a message.
target:
  entity_id: tts.google_translate_en_com
```
3. However, you can't use TTMG TTS with `tts.speak` - it works only with the voice assistant pipeline. Fixing this will break the previous point, so it is recommended to use native TTS integrations for `tts.speak` and TTMG TTS for the voice assistant pipeline. 

Not a deal-breaker for me personally, so I have not looked into making it work in a better way that would preserve this functionality. It might be easy to fix, it might be impossible - no idea at this point. 

Please describe your use case in the comments if this is a big problem for you and if there is enough demand, I will look into it.
